CREATE OR REPLACE FUNCTION FINANCE.LOGIC.RECOGNIZE_REVENUE(
    P_START_DATE DATE,
    P_END_DATE   DATE
)
RETURNS TABLE (
    CUSTOMER_ID             NUMBER(38, 0),
    BILLABLE_EVENT_ID       VARCHAR,
    RECOGNITION_DATE        DATE,
    EVENT_TYPE              VARCHAR,
    SOURCE_CURRENCY         VARCHAR,
    RECOGNIZED_REVENUE_USD  NUMBER(18, 2)
)
LANGUAGE SQL
AS
$$
    SELECT
        b.CUSTOMER_ID,
        b.BILLABLE_EVENT_ID,
        b.RECOGNITION_DATE,
        b.EVENT_TYPE,
        b.CURRENCY_CODE AS SOURCE_CURRENCY,
        fx.CONVERTED_AMOUNT AS RECOGNIZED_REVENUE_USD
    FROM FINANCE.DATASETS.FACT_BILLABLE_EVENTS AS b,
    LATERAL TABLE(
        FINANCE.LOGIC.NORMALIZE_CURRENCY(
            b.NET_AMOUNT,
            b.CURRENCY_CODE,
            'USD',
            b.RECOGNITION_DATE
        )
    ) AS fx
    WHERE b.RECOGNITION_DATE BETWEEN P_START_DATE AND P_END_DATE
      AND b.IS_RECOGNIZABLE = TRUE
$$;
